apiVersion: apps/v1
kind: Deployment
metadata:
  name: deplo-gvq
  namespace: default
spec:
  selector:
    matchLabels:
      app: deplo-gvq
  replicas: 1
  template:
    metadata:
      labels:
        app: deplo-gvq
    spec:
      containers:
        - name: deplo-gvq
          image: gvqocsqlk8s
          resources:
            requests:
              memory: '16Mi'
              cpu: '50m'
            limits:
              memory: '32Mi'
              cpu: '60m'
          imagePullPolicy: IfNotPresent