apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: dockerhub
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: dockerhub
            image: docker.io/atoro77/python3:dockerhub
            imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure