apiVersion: v1
kind: Service
metadata:
  labels:
    app: empty
  name: empty
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: empty
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: empty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empty
  template:
    metadata:
      labels:
        app: empty
    spec:
      containers:
      - name: empty
        image: docker.io/python:3.6-alpine3.12
        imagePullPolicy: Always
      restartPolicy: Always
