origin_host='172.19.182.100'
origin_port='1521'
origin_serviceName='POWA1'
orgin_database='GVQ_VIEW'
origin_user='monitor'
origin_password='M0n1t0r'

#destination_host='abi-las-prd-brs-indicadoresops-sql.database.windows.net' ###'localhost' ###'abi-las-prd-brs-indicadoresops-sql.database.windows.net'
#destination_driver='DRIVER={ODBC Driver 17 for SQL Server};SERVER='
#destination_database='ABI.DB.IndicadoresOps'###'BXO'
#destination_user='indicadoresOps'###'test'###'indicadoresOps'
#destination_password='PP<d2)$6Kz$9p!Ht'###'Cornfield30!'###'PP<d2)$6Kz$9p!Ht'

#destination_host='localhost'
#destination_driver='DRIVER={ODBC Driver 17 for SQL Server};SERVER='
#destination_database='BXO'
#destination_user='test'
#destination_password='Cornfield30!'

destination_host='127.0.0.1'
destination_driver='DRIVER={ODBC Driver 17 for SQL Server};SERVER='
destination_database='visual'
destination_user='sa'
destination_password='Conexion.2020'